In [97]:
# Not more than one datatype, if available it will convert it all to same datatype
import numpy as np

In [98]:
# Lists can have multiple datatypes
k = [1,2,3,"Hi",True]
print(k)
print(type(k))

[1, 2, 3, 'Hi', True]
<class 'list'>


In [99]:
# numpy array
k = np.array(k)
print(k)
print(type(k))

['1' '2' '3' 'Hi' 'True']
<class 'numpy.ndarray'>


In [100]:
# 2D Arrays
l = [[1,2,3],[4,5,6]]
l = np.array(l)
print(l)
print(type(l))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [101]:
print(l.shape)

(2, 3)


In [102]:
# To create empty array of defined size filled with zero
zarray = np.zeros(shape=(3,3))
print(zarray)
# To create empty array of defined size filled with one
oarray = np.ones(shape=(2,2))
print(oarray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [103]:
# Equivalent to in range expression in a loop
ar1 = np.arange(0,10)
print(ar1)
ar2 = np.arange(0,10,2) # Here 2 is the increment value
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [104]:
# Reverse Sequencing
ar3 = np.arange(6,0,-1)
print(ar3)

[6 5 4 3 2 1]


In [105]:
# Mean/Average value of Array
print(ar3.mean())

3.5


In [106]:
# Maximum value of array
print(ar3.max())
print(ar2.max())

6
8


In [107]:
# Index of Maximum value of array
print(ar3.argmax())
print(ar2.argmax())

0
4


In [108]:
# Minimum value of array
print(ar3.min())
print(ar2.min())

1
0


In [109]:
# Index of Minimum value of array
print(ar3.argmin())
print(ar2.argmin())

5
0


In [110]:
# Reshaping of arrays
print(ar3)
print(ar3.shape)
ar4 = ar3.reshape(6,1)
print(ar4)
print(ar4.shape)

[6 5 4 3 2 1]
(6,)
[[6]
 [5]
 [4]
 [3]
 [2]
 [1]]
(6, 1)


In [111]:
print(ar3.shape)
print(ar4.shape)

(6,)
(6, 1)
